[general]
import = ["/home/lro/.config/alacritty/catppuccin/catppuccin-mocha.toml"]

[window]
padding = { x = 10, y = 10 }
dynamic_padding = true
opacity = 0.85
blur = true
decorations = "None"

[font]
size = 12.0

[font.normal]
family = "JetBrainsMono Nerd Font"
style = "Regular"

[font.bold]
family = "JetBrainsMono Nerd Font"
style = "Bold"

[font.italic]
family = "JetBrainsMono Nerd Font"
style = "Italic"

[cursor]
style = { shape = "Block", blinking = "Always" }
blink_interval = 750

[terminal.shell]
program = "/usr/bin/tmux"

[env]
TERM = "alacritty"
